# .github/workflows/ci.yml
name: CI Workflow Belajar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode dari repo
      uses: actions/checkout@v3

    - name: Jalankan perintah CI
      run: |
        echo "ğŸš€ CI/CD Berjalan di GitHub Actions!"
        echo "ğŸ“ Direktori saat ini: $(pwd)"
        ls -la
